replicaCount: 2
namespace: stage-proxy
image:
  repository: nginx
  tag: latest
  imagePullPolicy: IfNotPresent
service:
  type: LoadBalancer
config:
  nginxConf: |
    server {
      listen 80;
      location / {
        proxy_pass http://stage-wordpress-app.wp.svc.cluster.local:80;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    }
