wp:
  name: wordpress-app
  labels:
    app: wp
    env: dev
    stack: wordpress
    id: c0916667
  image:
    repository: wordpress
    tag: latest
    imagePullPolicy: IfNotPresent

  replicas: 10
  configmap:
    ## KEY: "value"
    APP_ENV: "dev"
    WORDPRESS_DB_HOST: "wp-database.wpdb.svc.cluster.local"
    WORDPRESS_DB_NAME: "wordpress"
    WORDPRESS_DB_USER: "wordpress"
  containerPorts:
      http: 80
