db:
  labels:
    app: db
    env: dev
    stack: wordpress
    id: c0916667
  image:
    repository:  mariadb
    tag: 10.6.4-focal
    pullPolicy: Always
  replicas: 1
  configmap:
    ## KEY: "value"
    MYSQL_DATABASE: wordpress
    MYSQL_USER: wordpress
    MARIADB_ROOT_PASSWORD: wordpress
    APP_ENV: dev
  containerPorts:
      mysql: 3306
